<?xml version="1.0" encoding="UTF-8"?><testsuite name="Chrome_390217171_Mac_OS.localStorageWrapper" errors="1" failures="0" tests="1" time="0.001">
<testcase classname="Chrome_390217171_Mac_OS.localStorageWrapper" name="test test for wrapper function" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/localStorageWrapper_test.js:16:24)\n    at QUnitTestCase.(anonymous function) [as test test for wrapper function] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/localStorageWrapper_test.js:16:24)\n    at QUnitTestCase.(anonymous function) [as test test for wrapper function] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/localStorageWrapper_test.js:16:24)\n    at QUnitTestCase.(anonymous function) [as test test for wrapper function] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at jstestdriver.PluginRegistrar.dispatch_ (http://localhost:9876/static/runner.js:1603:26)"}]</error>
</testcase>
</testsuite>
